AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - "vendor/**/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "seekmodo-sdk.gemspec"

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 200
